version: "3"
services:
    vizxub:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: vizxub
        restart: unless-stopped
        env_file:
            - .env
